const quizData = {
  colors: [
    { word: "blue", correct: 0, options: ["azul", "morado", "rosa", "negro"] },
    { word: "pink", correct: 1, options: ["morado", "rosa", "gris", "blanco"] },
    { word: "red", correct: 2, options: ["verde", "azul", "rojo", "gris"] },
    { word: "green", correct: 3, options: ["amarillo", "negro", "naranja", "verde"] },
    { word: "yellow", correct: 0, options: ["amarillo", "rojo", "azul", "marron"] },
    { word: "black", correct: 1, options: ["blanco", "negro", "rosa", "verde"] },
    { word: "white", correct: 2, options: ["gris", "morado", "blanco", "naranja"] },
    { word: "purple", correct: 3, options: ["rojo", "marron", "amarillo", "morado"] },
    { word: "orange", correct: 0, options: ["naranja", "azul", "blanco", "rosa"] },
    { word: "brown", correct: 2, options: ["verde", "negro", "marron", "gris"] }
  ],
  animals: [
    { word: "dog", correct: 0, options: ["perro", "gato", "pez", "pajaro"] },
    { word: "cat", correct: 1, options: ["conejo", "gato", "vaca", "caballo"] },
    { word: "bird", correct: 2, options: ["pez", "oso", "pajaro", "mono"] },
    { word: "fish", correct: 3, options: ["leon", "perro", "gato", "pez"] },
    { word: "horse", correct: 0, options: ["caballo", "vaca", "oso", "conejo"] },
    { word: "cow", correct: 1, options: ["mono", "vaca", "pez", "pajaro"] },
    { word: "lion", correct: 2, options: ["oso", "conejo", "leon", "gato"] },
    { word: "rabbit", correct: 3, options: ["caballo", "leon", "perro", "conejo"] },
    { word: "monkey", correct: 0, options: ["mono", "pajaro", "vaca", "pez"] },
    { word: "bear", correct: 2, options: ["gato", "conejo", "oso", "caballo"] }
  ],
  numbers: [
    { word: "one", correct: 0, options: ["uno", "dos", "tres", "cuatro"] },
    { word: "two", correct: 1, options: ["cinco", "dos", "uno", "seis"] },
    { word: "three", correct: 2, options: ["ocho", "nueve", "tres", "siete"] },
    { word: "four", correct: 3, options: ["uno", "diez", "seis", "cuatro"] },
    { word: "five", correct: 0, options: ["cinco", "dos", "nueve", "ocho"] },
    { word: "six", correct: 1, options: ["siete", "seis", "tres", "cuatro"] },
    { word: "seven", correct: 2, options: ["ocho", "cinco", "siete", "dos"] },
    { word: "eight", correct: 3, options: ["tres", "seis", "uno", "ocho"] },
    { word: "nine", correct: 0, options: ["nueve", "diez", "cinco", "cuatro"] },
    { word: "ten", correct: 2, options: ["siete", "tres", "diez", "dos"] }
  ],
  objects: [
    { word: "table", correct: 0, options: ["mesa", "silla", "puerta", "libro"] },
    { word: "chair", correct: 1, options: ["ventana", "silla", "botella", "lapiz"] },
    { word: "book", correct: 2, options: ["coche", "llave", "libro", "telefono"] },
    { word: "pencil", correct: 3, options: ["puerta", "mesa", "silla", "lapiz"] },
    { word: "door", correct: 0, options: ["puerta", "ventana", "libro", "coche"] },
    { word: "window", correct: 1, options: ["llave", "ventana", "botella", "mesa"] },
    { word: "car", correct: 2, options: ["telefono", "lapiz", "coche", "puerta"] },
    { word: "key", correct: 3, options: ["silla", "libro", "ventana", "llave"] },
    { word: "bottle", correct: 0, options: ["botella", "telefono", "mesa", "coche"] },
    { word: "phone", correct: 2, options: ["llave", "puerta", "telefono", "libro"] }
  ],
  words: [
    { word: "take", correct: 0, options: ["tomar", "dejar", "romper", "cerrar"] },
    { word: "down", correct: 1, options: ["arriba", "abajo", "lado", "centro"] },
    { word: "all", correct: 2, options: ["nada", "poco", "todo", "mitad"] },
    { word: "mirrors", correct: 0, options: ["espejos", "puertas", "mesas", "paredes"] },
    { word: "house", correct: 1, options: ["calle", "casa", "edificio", "cuarto"] },
    { word: "hate", correct: 2, options: ["amar", "querer", "odiar", "sentir"] },
    { word: "nose", correct: 0, options: ["nariz", "ojo", "boca", "cara"] },
    { word: "eyes", correct: 1, options: ["manos", "ojos", "piernas", "brazos"] },
    { word: "mouth", correct: 3, options: ["cabeza", "oido", "nariz", "boca"] },
    { word: "jokes", correct: 2, options: ["historias", "cuentos", "bromas", "mentiras"] },
    { word: "laugh", correct: 1, options: ["llorar", "reir", "gritar", "hablar"] },
    { word: "calls", correct: 0, options: ["llama", "escribe", "busca", "corre"] },
    { word: "phone", correct: 2, options: ["television", "radio", "telefono", "tablet"] },
    { word: "ringing", correct: 3, options: ["caminando", "gritando", "mirando", "sonando"] },
    { word: "baby", correct: 1, options: ["amigo", "bebe", "mama", "papa"] },
    { word: "leave", correct: 0, options: ["dejar", "entrar", "volver", "seguir"] },
    { word: "alone", correct: 2, options: ["juntos", "felices", "solo", "rapido"] },
    { word: "saw", correct: 1, options: ["hizo", "vio", "tomo", "corrio"] },
    { word: "flaws", correct: 3, options: ["virtudes", "logros", "metas", "defectos"] },
    { word: "tell", correct: 0, options: ["decir", "escuchar", "ver", "sentir"] },
    { word: "wrong", correct: 2, options: ["bien", "igual", "mal", "correcto"] },
    { word: "feeling", correct: 1, options: ["pensar", "sentir", "mirar", "crear"] },
    { word: "doubts", correct: 3, options: ["certezas", "ideas", "metas", "dudas"] },
    { word: "wanna", correct: 0, options: ["querer", "poder", "hacer", "tener"] },
    { word: "die", correct: 2, options: ["vivir", "sonar", "morir", "correr"] },
    { word: "couch", correct: 1, options: ["mesa", "sofa", "cama", "silla"] },
    { word: "want", correct: 0, options: ["querer", "dar", "tener", "pedir"] },
    { word: "never", correct: 3, options: ["siempre", "a veces", "quiza", "nunca"] },
    { word: "good", correct: 1, options: ["malo", "bueno", "feo", "lento"] },
    { word: "anything", correct: 2, options: ["algo", "todo", "cualquier cosa", "nada"] },
    { word: "talk", correct: 0, options: ["hablar", "correr", "saltar", "mirar"] },
    { word: "buy", correct: 3, options: ["vender", "usar", "romper", "comprar"] },
    { word: "wedding", correct: 1, options: ["fiesta", "boda", "reunion", "evento"] },
    { word: "ring", correct: 2, options: ["pulsera", "collar", "anillo", "arete"] },
    { word: "question", correct: 0, options: ["pregunta", "respuesta", "duda", "idea"] },
    { word: "matter", correct: 3, options: ["cosa", "vida", "problema", "importar"] },
    { word: "outside", correct: 1, options: ["adentro", "afuera", "lejos", "cerca"] },
    { word: "laughing", correct: 2, options: ["llorando", "gritando", "riendo", "callado"] },
    { word: "another", correct: 0, options: ["otro", "mismo", "igual", "nuevo"] },
    { word: "dude", correct: 3, options: ["nino", "hombre", "amigo", "tipo"] },
    { word: "make", correct: 1, options: ["romper", "hacer", "crear", "armar"] },
    { word: "face", correct: 2, options: ["mano", "pie", "cara", "ojo"] },
    { word: "feel", correct: 0, options: ["sentir", "ver", "oir", "pensar"] },
    { word: "ghost", correct: 3, options: ["monstruo", "demonio", "alma", "fantasma"] }
  ]
};

if (typeof window !== "undefined") {
  window.quizData = quizData;
}
