const quizData = {
  colors: [
    { word: "blue", correct: 0, options: ["azul", "morado", "rosa", "negro"] },
    { word: "pink", correct: 1, options: ["morado", "rosa", "gris", "blanco"] },
    { word: "red", correct: 2, options: ["verde", "azul", "rojo", "gris"] },
    { word: "green", correct: 3, options: ["amarillo", "negro", "naranja", "verde"] },
    { word: "yellow", correct: 0, options: ["amarillo", "rojo", "azul", "marron"] },
    { word: "black", correct: 1, options: ["blanco", "negro", "rosa", "verde"] },
    { word: "white", correct: 2, options: ["gris", "morado", "blanco", "naranja"] },
    { word: "purple", correct: 3, options: ["rojo", "marron", "amarillo", "morado"] },
    { word: "orange", correct: 0, options: ["naranja", "azul", "blanco", "rosa"] },
    { word: "brown", correct: 2, options: ["verde", "negro", "marron", "gris"] },
    { word: "gray", correct: 1, options: ["negro", "gris", "blanco", "azul"] },
    { word: "gold", correct: 0, options: ["dorado", "plateado", "amarillo", "marron"] },
    { word: "silver", correct: 2, options: ["gris", "blanco", "plateado", "negro"] },
    { word: "beige", correct: 3, options: ["gris", "blanco", "amarillo", "beige"] },
    { word: "cyan", correct: 1, options: ["azul", "cian", "verde", "turquesa"] },
    { word: "magenta", correct: 0, options: ["magenta", "rosa", "rojo", "morado"] },
    { word: "turquoise", correct: 2, options: ["verde", "azul", "turquesa", "cian"] },
    { word: "navy", correct: 3, options: ["azul", "negro", "gris", "azul marino"] },
    { word: "lime", correct: 0, options: ["verde lima", "verde", "amarillo", "cian"] },
    { word: "violet", correct: 0, options: ["violeta", "morado", "rosa", "azul"] },
    { word: "peach", correct: 2, options: ["rosa", "naranja", "durazno", "amarillo"] },
    { word: "mint", correct: 1, options: ["verde", "menta", "cian", "blanco"] },
    { word: "lavender", correct: 3, options: ["rosa", "lila", "morado", "lavanda"] },
  ],
  animals: [
    { word: "dog", correct: 0, options: ["perro", "gato", "pez", "pajaro"] },
    { word: "cat", correct: 1, options: ["conejo", "gato", "vaca", "caballo"] },
    { word: "bird", correct: 2, options: ["pez", "oso", "pajaro", "mono"] },
    { word: "fish", correct: 3, options: ["leon", "perro", "gato", "pez"] },
    { word: "horse", correct: 0, options: ["caballo", "vaca", "oso", "conejo"] },
    { word: "cow", correct: 1, options: ["mono", "vaca", "pez", "pajaro"] },
    { word: "lion", correct: 2, options: ["oso", "conejo", "leon", "gato"] },
    { word: "rabbit", correct: 3, options: ["caballo", "leon", "perro", "conejo"] },
    { word: "monkey", correct: 0, options: ["mono", "pajaro", "vaca", "pez"] },
    { word: "bear", correct: 2, options: ["gato", "conejo", "oso", "caballo"] }
  ],
  numbers: [
    { word: "one", correct: 0, options: ["uno", "dos", "tres", "cuatro"] },
    { word: "two", correct: 1, options: ["cinco", "dos", "uno", "seis"] },
    { word: "three", correct: 2, options: ["ocho", "nueve", "tres", "siete"] },
    { word: "four", correct: 3, options: ["uno", "diez", "seis", "cuatro"] },
    { word: "five", correct: 0, options: ["cinco", "dos", "nueve", "ocho"] },
    { word: "six", correct: 1, options: ["siete", "seis", "tres", "cuatro"] },
    { word: "seven", correct: 2, options: ["ocho", "cinco", "siete", "dos"] },
    { word: "eight", correct: 3, options: ["tres", "seis", "uno", "ocho"] },
    { word: "nine", correct: 0, options: ["nueve", "diez", "cinco", "cuatro"] },
    { word: "ten", correct: 2, options: ["siete", "tres", "diez", "dos"] }
  ],
  objects: [
    { word: "think", correct: 0, options: ["pensar", "decir", "mirar", "creer"] },
    { word: "sorry", correct: 1, options: ["gracias", "perdón", "hola", "adiós"] },
    { word: "turning", correct: 2, options: ["correr", "saltar", "girar", "hablar"] },
    { word: "tables", correct: 3, options: ["sillas", "puertas", "camas", "mesas"] },
    { word: "chances", correct: 0, options: ["oportunidades", "errores", "ideas", "cosas"] },
    { word: "give", correct: 1, options: ["tomar", "dar", "dejar", "hacer"] },
    { word: "ask", correct: 2, options: ["responder", "decir", "preguntar", "pensar"] },
    { word: "goes", correct: 3, options: ["viene", "entra", "sale", "va"] },
    { word: "knows", correct: 0, options: ["sabe", "cree", "piensa", "mira"] },
    { word: "thinking", correct: 1, options: ["hablando", "pensando", "mirando", "riendo"] },
    { word: "words", correct: 2, options: ["frases", "letras", "palabras", "nombres"] },
    { word: "regret", correct: 3, options: ["olvidar", "amar", "pensar", "arrepentir"] },
    { word: "fire", correct: 0, options: ["fuego", "agua", "aire", "tierra"] },
    { word: "head", correct: 1, options: ["mano", "cabeza", "pie", "brazo"] },
    { word: "heard", correct: 2, options: ["ver", "decir", "escuchar", "hablar"] },
    { word: "accusation", correct: 3, options: ["defensa", "verdad", "error", "acusación"] },
    { word: "sun", correct: 0, options: ["sol", "luna", "estrella", "cielo"] },
    { word: "eyes", correct: 1, options: ["nariz", "ojos", "boca", "orejas"] },
    { word: "lies", correct: 2, options: ["verdades", "hechos", "mentiras", "ideas"] },
    { word: "believing", correct: 3, options: ["viendo", "escuchando", "pensando", "creyendo"] },
    { word: "eye", correct: 0, options: ["ojo", "mano", "cara", "pie"] },
    { word: "sky", correct: 1, options: ["mar", "cielo", "tierra", "nube"] },
    { word: "looking", correct: 2, options: ["corriendo", "saltando", "mirando", "durmiendo"] },
    { word: "read", correct: 3, options: ["escribir", "hablar", "escuchar", "leer"] },
    { word: "mind", correct: 0, options: ["mente", "cuerpo", "alma", "cerebro"] },
    { word: "maker", correct: 1, options: ["usuario", "creador", "lector", "jugador"] },
    { word: "rules", correct: 2, options: ["leyes", "juegos", "reglas", "ideas"] },
    { word: "fools", correct: 3, options: ["sabios", "niños", "adultos", "tontos"] },
    { word: "cheat", correct: 0, options: ["engañar", "ganar", "perder", "jugar"] },
    { word: "blind", correct: 1, options: ["ver", "ciego", "mirar", "notar"] },
    { word: "leave", correct: 2, options: ["entrar", "llegar", "dejar", "seguir"] },
    { word: "false", correct: 3, options: ["real", "cierto", "correcto", "falso"] },
    { word: "illusions", correct: 0, options: ["ilusiones", "verdades", "cosas", "ideas"] },
    { word: "cry", correct: 1, options: ["reír", "llorar", "hablar", "correr"] },
    { word: "changing", correct: 2, options: ["viendo", "pensando", "cambiando", "creciendo"] },
    { word: "find", correct: 3, options: ["buscar", "mirar", "perder", "encontrar"] },
    { word: "live", correct: 0, options: ["vivir", "morir", "existir", "sentir"] },
    { word: "signs", correct: 1, options: ["letras", "señales", "palabras", "números"] },
    { word: "deceiving", correct: 2, options: ["ayudando", "creyendo", "engañando", "mirando"] }
  ],
  words: [
    { word: "take", correct: 0, options: ["tomar", "dejar", "romper", "cerrar"] },
    { word: "down", correct: 1, options: ["arriba", "abajo", "lado", "centro"] },
    { word: "all", correct: 2, options: ["nada", "poco", "todo", "mitad"] },
    { word: "mirrors", correct: 0, options: ["espejos", "puertas", "mesas", "paredes"] },
    { word: "house", correct: 1, options: ["calle", "casa", "edificio", "cuarto"] },
    { word: "hate", correct: 2, options: ["amar", "querer", "odiar", "sentir"] },
    { word: "nose", correct: 0, options: ["nariz", "ojo", "boca", "cara"] },
    { word: "eyes", correct: 1, options: ["manos", "ojos", "piernas", "brazos"] },
    { word: "mouth", correct: 3, options: ["cabeza", "oido", "nariz", "boca"] },
    { word: "jokes", correct: 2, options: ["historias", "cuentos", "bromas", "mentiras"] },
    { word: "laugh", correct: 1, options: ["llorar", "reir", "gritar", "hablar"] },
    { word: "calls", correct: 0, options: ["llama", "escribe", "busca", "corre"] },
    { word: "phone", correct: 2, options: ["television", "radio", "telefono", "tablet"] },
    { word: "ringing", correct: 3, options: ["caminando", "gritando", "mirando", "sonando"] },
    { word: "baby", correct: 1, options: ["amigo", "bebe", "mama", "papa"] },
    { word: "leave", correct: 0, options: ["dejar", "entrar", "volver", "seguir"] },
    { word: "alone", correct: 2, options: ["juntos", "felices", "solo", "rapido"] },
    { word: "saw", correct: 1, options: ["hizo", "vio", "tomo", "corrio"] },
    { word: "flaws", correct: 3, options: ["virtudes", "logros", "metas", "defectos"] },
    { word: "tell", correct: 0, options: ["decir", "escuchar", "ver", "sentir"] },
    { word: "wrong", correct: 2, options: ["bien", "igual", "mal", "correcto"] },
    { word: "feeling", correct: 1, options: ["pensar", "sentir", "mirar", "crear"] },
    { word: "doubts", correct: 3, options: ["certezas", "ideas", "metas", "dudas"] },
    { word: "wanna", correct: 0, options: ["querer", "poder", "hacer", "tener"] },
    { word: "die", correct: 2, options: ["vivir", "sonar", "morir", "correr"] },
    { word: "couch", correct: 1, options: ["mesa", "sofa", "cama", "silla"] },
    { word: "want", correct: 0, options: ["querer", "dar", "tener", "pedir"] },
    { word: "never", correct: 3, options: ["siempre", "a veces", "quiza", "nunca"] },
    { word: "good", correct: 1, options: ["malo", "bueno", "feo", "lento"] },
    { word: "anything", correct: 2, options: ["algo", "todo", "cualquier cosa", "nada"] },
    { word: "talk", correct: 0, options: ["hablar", "correr", "saltar", "mirar"] },
    { word: "buy", correct: 3, options: ["vender", "usar", "romper", "comprar"] },
    { word: "wedding", correct: 1, options: ["fiesta", "boda", "reunion", "evento"] },
    { word: "ring", correct: 2, options: ["pulsera", "collar", "anillo", "arete"] },
    { word: "question", correct: 0, options: ["pregunta", "respuesta", "duda", "idea"] },
    { word: "matter", correct: 3, options: ["cosa", "vida", "problema", "importar"] },
    { word: "outside", correct: 1, options: ["adentro", "afuera", "lejos", "cerca"] },
    { word: "laughing", correct: 2, options: ["llorando", "gritando", "riendo", "callado"] },
    { word: "another", correct: 0, options: ["otro", "mismo", "igual", "nuevo"] },
    { word: "dude", correct: 3, options: ["nino", "hombre", "amigo", "tipo"] },
    { word: "make", correct: 1, options: ["romper", "hacer", "crear", "armar"] },
    { word: "face", correct: 2, options: ["mano", "pie", "cara", "ojo"] },
    { word: "feel", correct: 0, options: ["sentir", "ver", "oir", "pensar"] },
    { word: "ghost", correct: 3, options: ["monstruo", "demonio", "alma", "fantasma"] },
    { word: "run", correct: 0, options: ["correr", "caminar", "saltar", "parar"] },
    { word: "walk", correct: 1, options: ["correr", "caminar", "volar", "nadar"] },
    { word: "jump", correct: 2, options: ["caer", "rodar", "saltar", "subir"] },
    { word: "sleep", correct: 3, options: ["comer", "beber", "soñar", "dormir"] },
    { word: "eat", correct: 0, options: ["comer", "beber", "probar", "cocinar"] },
    { word: "drink", correct: 1, options: ["comer", "beber", "servir", "llenar"] },
    { word: "cook", correct: 2, options: ["lavar", "cortar", "cocinar", "freir"] },
    { word: "clean", correct: 3, options: ["ensuciar", "romper", "usar", "limpiar"] },
    { word: "open", correct: 0, options: ["abrir", "cerrar", "romper", "mover"] },
    { word: "close", correct: 1, options: ["abrir", "cerrar", "tirar", "empujar"] },
    { word: "push", correct: 2, options: ["jalar", "mover", "empujar", "parar"] },
    { word: "pull", correct: 3, options: ["empujar", "soltar", "romper", "jalar"] },
    { word: "fast", correct: 0, options: ["rapido", "lento", "grande", "fuerte"] },
    { word: "slow", correct: 1, options: ["rapido", "lento", "alto", "bajo"] },
    { word: "big", correct: 2, options: ["pequeno", "mediano", "grande", "alto"] },
    { word: "small", correct: 3, options: ["grande", "largo", "alto", "pequeno"] },
    { word: "happy", correct: 0, options: ["feliz", "triste", "enojado", "cansado"] },
    { word: "sad", correct: 1, options: ["feliz", "triste", "emocionado", "calmado"] },
    { word: "angry", correct: 2, options: ["feliz", "triste", "enojado", "asustado"] },
    { word: "tired", correct: 3, options: ["activo", "rapido", "fuerte", "cansado"] },
    { word: "love", correct: 0, options: ["amar", "odiar", "sentir", "querer"] },
    { word: "hate", correct: 1, options: ["amar", "odiar", "querer", "sentir"] },
    { word: "think", correct: 2, options: ["sentir", "ver", "pensar", "hablar"] },
    { word: "know", correct: 3, options: ["pensar", "creer", "ver", "saber"] },
    { word: "find", correct: 0, options: ["encontrar", "buscar", "perder", "ver"] },
    { word: "lose", correct: 1, options: ["ganar", "perder", "romper", "tirar"] },
    { word: "win", correct: 2, options: ["perder", "jugar", "ganar", "intentar"] },
    { word: "try", correct: 3, options: ["ganar", "perder", "hacer", "intentar"] },
    { word: "start", correct: 0, options: ["empezar", "terminar", "seguir", "parar"] },
    { word: "finish", correct: 1, options: ["empezar", "terminar", "pausar", "cerrar"] },
    { word: "continue", correct: 2, options: ["parar", "terminar", "continuar", "cerrar"] },
    { word: "stop", correct: 3, options: ["seguir", "correr", "hacer", "parar"] },
    { word: "help", correct: 0, options: ["ayudar", "molestar", "usar", "ver"] },
    { word: "need", correct: 1, options: ["querer", "necesitar", "tener", "pedir"] },
    { word: "give", correct: 2, options: ["recibir", "tomar", "dar", "dejar"] },
    { word: "take", correct: 3, options: ["dar", "ver", "usar", "tomar"] },
    { word: "table", correct: 0, options: ["mesa", "silla", "puerta", "libro"] },
    { word: "chair", correct: 1, options: ["ventana", "silla", "botella", "lapiz"] },
    { word: "book", correct: 2, options: ["coche", "llave", "libro", "telefono"] },
    { word: "pencil", correct: 3, options: ["puerta", "mesa", "silla", "lapiz"] },
    { word: "door", correct: 0, options: ["puerta", "ventana", "libro", "coche"] },
    { word: "window", correct: 1, options: ["llave", "ventana", "botella", "mesa"] },
    { word: "car", correct: 2, options: ["telefono", "lapiz", "coche", "puerta"] },
    { word: "key", correct: 3, options: ["silla", "libro", "ventana", "llave"] },
    { word: "bottle", correct: 0, options: ["botella", "telefono", "mesa", "coche"] },
    { word: "phone", correct: 2, options: ["llave", "puerta", "telefono", "libro"] },
    { word: "lamp", correct: 0, options: ["lampara", "mesa", "silla", "puerta"] },
    { word: "bed", correct: 1, options: ["sofa", "cama", "mesa", "puerta"] },
    { word: "sofa", correct: 2, options: ["cama", "silla", "sofa", "mesa"] },
    { word: "television", correct: 3, options: ["radio", "telefono", "tablet", "television"] },
    { word: "computer", correct: 0, options: ["computadora", "telefono", "pantalla", "teclado"] },
    { word: "keyboard", correct: 1, options: ["raton", "teclado", "pantalla", "bocina"] },
    { word: "mouse", correct: 2, options: ["teclado", "pantalla", "raton", "cable"] },
    { word: "screen", correct: 3, options: ["teclado", "raton", "bocina", "pantalla"] },
    { word: "pen", correct: 0, options: ["pluma", "lapiz", "borrador", "cuaderno"] },
    { word: "eraser", correct: 1, options: ["pluma", "borrador", "libro", "regla"] },
    { word: "notebook", correct: 2, options: ["libro", "hoja", "cuaderno", "lapiz"] },
    { word: "backpack", correct: 3, options: ["bolsa", "maleta", "caja", "mochila"] },
    { word: "glass", correct: 0, options: ["vaso", "botella", "taza", "plato"] },
    { word: "plate", correct: 1, options: ["cuchara", "plato", "tenedor", "vaso"] },
    { word: "spoon", correct: 2, options: ["tenedor", "cuchillo", "cuchara", "plato"] },
    { word: "fork", correct: 3, options: ["cuchara", "cuchillo", "plato", "tenedor"] },
    { word: "knife", correct: 0, options: ["cuchillo", "tenedor", "cuchara", "plato"] },
    { word: "cup", correct: 1, options: ["vaso", "taza", "plato", "botella"] },
    { word: "mirror", correct: 2, options: ["puerta", "ventana", "espejo", "pared"] },
    { word: "clock", correct: 3, options: ["reloj", "calendario", "alarma", "reloj de pared"] },
    { word: "fan", correct: 0, options: ["ventilador", "aire", "luz", "calor"] },
    { word: "air conditioner", correct: 1, options: ["ventilador", "aire acondicionado", "calefaccion", "luz"] },
    { word: "heater", correct: 2, options: ["ventilador", "aire", "calentador", "luz"] },
    { word: "light", correct: 3, options: ["sombra", "foco", "energia", "luz"] },
    { word: "bag", correct: 0, options: ["bolsa", "mochila", "caja", "maleta"] },
    { word: "box", correct: 1, options: ["bolsa", "caja", "maleta", "contenedor"] },
    { word: "wallet", correct: 2, options: ["bolsa", "mochila", "cartera", "caja"] },
    { word: "watch", correct: 3, options: ["reloj", "pulsera", "anillo", "reloj de mano"] },
    { word: "brush", correct: 0, options: ["cepillo", "peine", "toalla", "jabon"] },
    { word: "comb", correct: 1, options: ["cepillo", "peine", "toalla", "shampoo"] },
    { word: "towel", correct: 2, options: ["jabón", "cepillo", "toalla", "esponja"] },
    { word: "soap", correct: 3, options: ["agua", "toalla", "shampoo", "jabon"] }
  ]
};

if (typeof window !== "undefined") {
  window.quizData = quizData;
}
